name: test_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.3.5
  json_annotation: ^4.9.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  flutter_easyloading: ^3.0.5
  dio: ^5.7.0		
  build_runner: ^2.4.14
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  shimmer_animation: ^2.2.2
  file_picker: ^10.0.0
  package_info_plus: ^8.3.0
  device_info_plus: ^11.3.3
  connectivity_plus: ^6.1.3
  network_info_plus: ^6.1.3
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.8.0
  flutter_native_splash: ^2.4.6



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  jwt_decoder: ^2.0.1
  


flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/Rajesh_Dada.jpg"

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
  - lib/assets/Rajesh_Dada.jpg
  - lib/assets/rajeshDada1jpg.jpg
  - lib/assets/rajeshDada2jpg.jpg
  - lib/assets/rajeshDada3jpg.jpg
  - lib/assets/rajeshDada4jpg.jpg
  - lib/assets/dada_landing_photo.jpeg
  - lib/assets/bg_image.jpeg
  - lib/assets/hm_img.jpeg
  - lib/assets/Rajesh_dada_101.jpeg
  - lib/assets/Rajesh_dada_103.jpeg
  - lib/assets/Rajesh_dada_104.jpeg
  - lib/assets/Rajesh_dada_106.jpeg
  - lib/assets/rajesh_dada_201.jpeg
  - lib/assets/rajesh_dada_202.jpeg
  - lib/assets/rajesh_dada_203.jpeg
  - lib/assets/rajesh_dada_204.jpeg
  - lib/assets/rajesh_dada_205.jpeg
  - lib/assets/rajesh_dada_301.jpeg
  - lib/assets/Gallery/amoni_aasharam.jpeg
  - lib\assets\Gallery\birsa_munda.jpeg
  - lib/assets/Gallery/p_k_patil.jpeg
  - lib/assets/Gallery/raksha_bandhan.jpeg
  - lib/assets/Gallery/ranipur_info.jpeg


  - lib\assets\women_empowerment\bachatgat_meeting.jpeg
  - lib\assets\women_empowerment\bachatgat.jpeg
  - lib\assets\women_empowerment\kalawati_foundation.jpeg
  - lib\assets\women_empowerment\morwad_mahile_charcha.jpeg
  - lib\assets\women_empowerment\morwad.jpeg
  - lib\assets\women_empowerment\ranjanpur_prasad.jpeg
  - lib\assets\women_empowerment\savitribai_phule_jayanti.jpeg
  - lib\assets\women_empowerment\women_day.jpeg
  - lib\assets\women_empowerment\mod_bachatgat_meeting.jpeg

  - lib\assets\Icons\dummy_profile_icon.png
  - lib/assets/splash_screen_img.png
  - lib\assets\Icons\achievements_icon.jpeg
  - lib\assets\Icons\gallery_icon.jpeg
  - lib\assets\Icons\grievance_icon.jpeg
  - lib\assets\Icons\helpline_icon.jpeg
  - lib\assets\rajesh_dada_info_img.jpeg






flutter_native_splash:
  color: "#ffffff"
  image: lib/assets/splash_screen_img.png  
  android: true
  ios: true
  web: true   


  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
