// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0OZaGir3LRosxR3J2jUYkHVMmn4eHFd4',
    appId: '1:8185634887:web:4f9af6694e37f0f04f5162',
    messagingSenderId: '8185634887',
    projectId: 'notification-cli-75c77',
    authDomain: 'notification-cli-75c77.firebaseapp.com',
    storageBucket: 'notification-cli-75c77.firebasestorage.app',
    measurementId: 'G-NX8E7B5ZSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0VUrnC2ReoJpt5KZI2-0c_ReU0eAGOlM',
    appId: '1:8185634887:android:a9bdc18d2159aafb4f5162',
    messagingSenderId: '8185634887',
    projectId: 'notification-cli-75c77',
    storageBucket: 'notification-cli-75c77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0nOQph9zI3IzyK9u6RXZrqW6DRY54RZg',
    appId: '1:8185634887:ios:7f42bad0ae08c08e4f5162',
    messagingSenderId: '8185634887',
    projectId: 'notification-cli-75c77',
    storageBucket: 'notification-cli-75c77.firebasestorage.app',
    iosBundleId: 'com.example.projSetup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0nOQph9zI3IzyK9u6RXZrqW6DRY54RZg',
    appId: '1:8185634887:ios:7f42bad0ae08c08e4f5162',
    messagingSenderId: '8185634887',
    projectId: 'notification-cli-75c77',
    storageBucket: 'notification-cli-75c77.firebasestorage.app',
    iosBundleId: 'com.example.projSetup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0OZaGir3LRosxR3J2jUYkHVMmn4eHFd4',
    appId: '1:8185634887:web:6203da9e8cc8320b4f5162',
    messagingSenderId: '8185634887',
    projectId: 'notification-cli-75c77',
    authDomain: 'notification-cli-75c77.firebaseapp.com',
    storageBucket: 'notification-cli-75c77.firebasestorage.app',
    measurementId: 'G-V2HGV5Y25D',
  );
}
